apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://5.6.7.8
  name: scratch
contexts:
- context:
    cluster: development
    namespace: storage
    user: developer
  name: dev-storage
- context:
    cluster: shouldNotChange
    namespace: shouldNotChange
    user: shouldNotChange
  name: exp-scratch
current-context: ""
kind: Config
preferences: {}
users:
- name: experimenter
  user:
    password: some-password
    username: exp